version: '3.7'

services:
  postgres:
    container_name: notebook_researcher_django_gres
    restart: always
    image: postgres
    ports:
    - "5480:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
    - /home/postgres/notebook_researcher:/var/lib/postgresql/data

