# Generated by Django 3.2.4 on 2021-06-20 20:45

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('is_archived', models.BooleanField(default=False, verbose_name='آیا آرشیو شده است؟')),
                ('text', models.TextField(verbose_name='متن')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='notebooks.notebook', verbose_name='جزوه مربوطه')),
            ],
            options={
                'verbose_name': 'خط',
                'verbose_name_plural': 'خطوط',
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('is_archived', models.BooleanField(default=False, verbose_name='آیا آرشیو شده است؟')),
                ('text', models.TextField(verbose_name='متن')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='notebooks.notebook', verbose_name='جزوه مربوطه')),
            ],
            options={
                'verbose_name': 'پاراگراف',
                'verbose_name_plural': 'پاراگراف\u200cها',
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SearchKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('is_archived', models.BooleanField(default=False, verbose_name='آیا آرشیو شده است؟')),
                ('word', models.CharField(max_length=1024, verbose_name='کلمه کلیدی')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchkeys', to='notebooks.notebook', verbose_name='جزوه مربوطه')),
            ],
            options={
                'verbose_name': 'کلید جستجو',
                'verbose_name_plural': 'کلید های جستجو',
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ParagraphInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('is_archived', models.BooleanField(default=False, verbose_name='آیا آرشیو شده است؟')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key', to='inverted_index.searchkey', verbose_name='کلید مربوطه')),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='inverted_index.paragraph', verbose_name='پاراگراف مربوطه')),
            ],
            options={
                'verbose_name': 'میانی پاراگرافی',
                'verbose_name_plural': 'میانی های پاراگرافی',
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LineInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('is_archived', models.BooleanField(default=False, verbose_name='آیا آرشیو شده است؟')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_interfaces', to='inverted_index.searchkey', verbose_name='کلید مربوطه')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='inverted_index.line', verbose_name='خط مربوطه')),
            ],
            options={
                'verbose_name': 'میانی خطی',
                'verbose_name_plural': 'میانی های خطی',
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
