# Generated by Django 3.2.4 on 2021-06-21 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('is_archived', models.BooleanField(default=False, verbose_name='آیا آرشیو شده است؟')),
                ('text', models.TextField(verbose_name='متن')),
                ('index', models.PositiveIntegerField(verbose_name='شماره اندیس')),
                ('index_type', models.CharField(choices=[('Line', 'خط'), ('PARAGRAPH', 'پاراگراف')], max_length=512, verbose_name='نوع اندیس')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexs', to='notebooks.notebook', verbose_name='جزوه مربوطه')),
            ],
            options={
                'verbose_name': 'اندیس',
                'verbose_name_plural': 'اندیس\u200cها',
                'unique_together': {('index', 'index_type', 'notebook')},
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('index_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inverted_index.index')),
            ],
            options={
                'verbose_name': 'خط',
                'verbose_name_plural': 'خطوط',
            },
            bases=('inverted_index.index',),
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('index_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inverted_index.index')),
            ],
            options={
                'verbose_name': 'پاراگراف',
                'verbose_name_plural': 'پاراگراف\u200cها',
            },
            bases=('inverted_index.index',),
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SearchKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('is_archived', models.BooleanField(default=False, verbose_name='آیا آرشیو شده است؟')),
                ('word', models.CharField(max_length=1024, verbose_name='کلمه کلیدی')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchkeys', to='notebooks.notebook', verbose_name='جزوه مربوطه')),
            ],
            options={
                'verbose_name': 'کلید جستجو',
                'verbose_name_plural': 'کلید های جستجو',
                'unique_together': {('word', 'notebook')},
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='IndexInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('is_archived', models.BooleanField(default=False, verbose_name='آیا آرشیو شده است؟')),
                ('repeat', models.PositiveIntegerField(default=1, verbose_name='تعداد تکرار')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='inverted_index.index', verbose_name='اندیس مربوطه')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_interfaces', to='inverted_index.searchkey', verbose_name='کلید مربوطه')),
            ],
            options={
                'verbose_name': 'میانی اندیس',
                'verbose_name_plural': 'میانی های اندیس',
            },
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
