# Generated by Django 3.2.4 on 2021-06-20 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
        ('inverted_index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='notebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='notebooks.notebook', verbose_name='جزوه مربوطه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paragraph',
            name='notebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='notebooks.notebook', verbose_name='جزوه مربوطه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchkey',
            name='notebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='searchkeys', to='notebooks.notebook', verbose_name='جزوه مربوطه'),
            preserve_default=False,
        ),
    ]
