from inverted_index.enums import INDEX_TYPE_LINE, INDEX_TYPE_PARAGRAPH

NOTEBOOK_VALID_FILE_EXTENSIONS = ['.txt']
PREVIEW_SIZE = 256

LINE_SEPARATOR = '.'
PARAGRAPH_SEPARATOR = '\n'
WORD_SEPARATOR = ' '

SEPARATOR_TO_INDEX = (
    (LINE_SEPARATOR, INDEX_TYPE_LINE),
    (PARAGRAPH_SEPARATOR, INDEX_TYPE_PARAGRAPH),
)